apiVersion: v1
kind: Service
metadata:
  name: sabnzbd 
  labels:
    {{- include "media-hunt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sabnzbd.service.type }}
  ports:
    - port: {{ .Values.sabnzbd.service.port }}
      targetPort: sabnzbd
      protocol: TCP
      name: sabnzbd
  selector:
    {{- include "media-hunt.selectorLabels" . | nindent 4 }}
