apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "radarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "radarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "radarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- range $k, $v := .Values.environment }}
          - name: {{ $k }}
            value: {{ $v | quote }}
          {{- end }}
          {{- if or .Values.persistence.enabled .Values.persistence.nfs_enabled }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
          - name: config
            mountPath: config 
          {{- end }}
          - name: downloads
            mountPath: /downloads
          - name: movies
            mountPath: /movies
          {{- end }}
      {{- if or .Values.persistence.enabled .Values.persistence.nfs_enabled }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: config
        persistentVolumeClaim:
          claimName: config
      {{- end }}
      - name: downloads
      {{- if .Values.persistence.nfs_enabled }}
        nfs:
          server: {{ .Values.persistence.server }}
          path: {{ .Values.persistence.downloads_path }}
      {{- else }}
        persistentVolumeClaim:
          claimName: downloads
      {{- end }}
      - name: movies
      {{- if .Values.persistence.nfs_enabled }}
        nfs:
          server: {{ .Values.persistence.server }}
          path: {{ .Values.persistence.movies_path }}
      {{- else }}
        persistentVolumeClaim:
          claimName: movies
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
